# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Avireni
tagline:          'A Jekyll theme'
description:      'I am a Web Geek.'
#description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://codesnipp.github.io
baseurl:          /

author:
  name:           'Venkata Jillella'
  url:            https://twitter.com/jillella

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/codesnipp/codesnipp.github.io
